project_id = "mroctuyjpoegijanxfam"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[functions.paystack-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.ai-matching]
verify_jwt = true