// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mroctuyjpoegijanxfam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yb2N0dXlqcG9lZ2lqYW54ZmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTExNzIsImV4cCI6MjA3NDEyNzE3Mn0.eJ0ZJ304Cfwc8EbLq3KWM2HRD7fodMhTf9ZbaS53mic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});